=== brechtvdv/transitland-feed-registry/lib/onestop_id_registry/schemas/operators.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Transitland Onestop-Registry Operator",
  "type": "object",
  "required": ["name", "onestopId", "geometry"],
  "properties": {
    "onestopId": {
      "type": "string",
      "format": "operatorOnestopId"
    },
    "name": { "type": "string" },
    "tags": { "type": "object" },
    "geometry": { "type": "object" },
    "identifiers": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["identifier"],
        "properties": {
          "identifier": { "type": "string" }
        }
      }
    }
  }
}

=== brechtvdv/transitland-feed-registry/operators/o-9q9-VTA.json
{
  "onestopId": "o-9q9-VTA",
  "name": "Santa Clara Valley Transportation Authority",
  "tags": {
    "us_national_transit_database_id": 9013,
    "website": "http://www.vta.org",
    "timezone": "America/Los_Angeles"
  },
  "identifiers": [
    { "identifier": "VTA" }
  ],
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-122.173638697,37.440556809],
      [-122.149990584,37.395450619],
      [-122.130937923,37.361408526],
      [-122.030939181,37.259406422],
      [-121.983920828,37.222231292],
      [-121.570633691,36.974922178],
      [-121.54902915,37.00006636],
      [-121.55177066,37.00582962],
      [-121.631097271,37.148849231],
      [-121.923956233,37.540138969],
      [-121.92699421,37.542184637],
      [-121.953170709,37.558388156],
      [-121.975949,37.557288],
      [-122.173568669,37.443449787],
      [-122.173638697,37.440556809]
    ]]
  }
}

=== brechtvdv/transitland-feed-registry/operators/o-9q9-SamTrans.json
{
  "onestopId": "o-9q9-SamTrans",
  "name": "San Mateo County Transit District",
  "tags": {
    "us_national_transit_database_id": 9009,
    "website": "http://www.samtrans.com",
    "timezone": "America/Los_Angeles"
  },
  "identifiers": [
    { "identifier": "SamTrans" }
  ],
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-122.51796,37.53556],
      [-122.412922,37.259608],
      [-122.3925,37.2503],
      [-122.382827,37.251686],
      [-122.21142,37.36789],
      [-122.19961,37.37708],
      [-122.194621,37.381745],
      [-122.12492,37.45734],
      [-122.13037,37.47045],
      [-122.13207,37.47271],
      [-122.39243,37.79009],
      [-122.39695,37.790137],
      [-122.39728,37.7901],
      [-122.41845,37.77518],
      [-122.48333,37.72698],
      [-122.485105,37.724185],
      [-122.49301,37.68985],
      [-122.515757,37.569983],
      [-122.51796,37.53556]
    ]]
  }
}

=== brechtvdv/transitland-feed-registry/operators/o-9q9-ACTransit.json
{
  "onestopId": "o-9q9-ACTransit",
  "name": "Alameda-Contra Costa Transit District",
  "tags": {
    "us_national_transit_database_id": 9014,
    "website": "http://www.actransit.org",
    "timezone": "America/Los_Angeles"
  },
  "identifiers": [
    { "identifier": "AC Transit" }
  ],
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-122.4219466,37.7728291],
      [-122.2998181,37.5351863],
      [-122.1487153,37.3938421],
      [-122.1458932,37.3934467],
      [-121.9001573,37.4138609],
      [-121.8941378,37.4317001],
      [-121.91129,37.530161],
      [-122.251045,37.9667104],
      [-122.2533713,37.9682723],
      [-122.3028331,37.9915676],
      [-122.3038451,37.9917478],
      [-122.3485642,37.9966206],
      [-122.349579,37.996726],
      [-122.3545248,37.9931709],
      [-122.3867859,37.9288703],
      [-122.4219466,37.7728291]
    ]]
  }
}
