=== brechtvdv/transitland-feed-registry/lib/transit-land-feed-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "TransitLand Feed",
  "type": "object",
  "required": ["url", "feedFormat", "operatorsInFeed"],
  "properties": {
    "url": {
      "type": "string",
      "format": "uri"
    },
    "feedFormat": { "type": "string" },
    "tags": { "type": "object" },
    "operatorsInFeed": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["operator", "gtfsAgencyId"],
        "properties": {
          "gtfsAgencyId": { "type": "string" },
          "operator": {
            "type": "object",
            "required": ["name", "onestop_id", "geometry"],
            "properties": {
              "onestop_id": {
                "type": "string",
                "format": "operatorOnestopId"
              },
              "name": { "type": "string" },
              "tags": { "type": "object" },
              "geometry": { "type": "object" },
              "identifiers": {
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                  "type": "object",
                  "required": ["identifier"],
                  "properties": {
                    "identifier": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== brechtvdv/transitland-feed-registry/data/us-ca-vta.json
{
  "url": "http://www.vta.org/sfc/servlet.shepherd/document/download/069A0000001NUea",
  "feedFormat": "gtfs",
  "tags": {
    "licenseUrl": "http://www.sfmta.com/about-sfmta/reports/gtfs-transit-data",
    "downloadPageUrl": "http://www.vta.org/getting-around/gtfs-info/data-file"
  },
  "operatorsInFeed": [
    {
      "operator": {
        "name": "Santa Clara Valley Transportation Authority",
        "tags": {
          "us_national_transit_database_id": 9013,
          "website": "http://www.vta.org",
          "timezone": "America/Los_Angeles"
        },
        "identifiers": [
          { "identifier": "VTA" }
        ],
        "onestop_id": "o-9q9-VTA",
        "geometry": {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-122.173638697,37.440556809],[-122.149990584,37.395450619],[-122.130937923,37.361408526],[-122.030939181,37.259406422],[-121.983920828,37.222231292],[-121.570633691,36.974922178],[-121.54902915,37.00006636],[-121.55177066,37.00582962],[-121.631097271,37.148849231],[-121.923956233,37.540138969],[-121.92699421,37.542184637],[-121.953170709,37.558388156],[-121.975949,37.557288],[-122.173568669,37.443449787],[-122.173638697,37.440556809]]]}}
      },
      "gtfsAgencyId": "VTA"
    }
  ]
}

=== brechtvdv/transitland-feed-registry/data/us-ca-sfmta.json
{
  "url": "http://archives.sfmta.com/transitdata/google_transit.zip",
  "feedFormat": "gtfs",
  "tags": {
    "licenseUrl": "http://www.sfmta.com/about-sfmta/reports/gtfs-transit-data"
  },
  "operatorsInFeed": [
    {
      "operator": {
        "name": "San Francisco Municipal Transportation Agency",
        "tags": {
          "us_national_transit_database_id": 9015,
          "website": "http://www.sfmta.com",
          "timezone": "America/Los_Angeles"
        },
        "identifiers": [
          { "identifier": "MUNI" },
          { "identifier": "SFMTA" }
        ],
        "onestop_id": "o-9q8y-SFMTA",
        "geometry": {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-122.53867,37.83238],[-122.506821,37.735482],[-122.500028,37.718996],[-122.499913,37.718738],[-122.49766,37.71677],[-122.485294,37.709312],[-122.48498,37.70913],[-122.469273,37.705764],[-122.413084,37.706296],[-122.39422,37.70898],[-122.392836,37.709804],[-122.365447,37.72792],[-122.36633,37.820001],[-122.371964,37.828311],[-122.373477,37.82982],[-122.48383,37.83592],[-122.50214,37.836443],[-122.53867,37.83238]]]}}
      },
      "gtfsAgencyId": "SFMTA"
    }
  ]
}

=== brechtvdv/transitland-feed-registry/data/us-ca-samtrans.json
{
  "url": "http://www.samtrans.com/Assets/GTFS/samtrans/SamTrans-GTFS-RB115-rev-08252014.zip",
  "feedFormat": "gtfs",
  "tags": {
    "licenseUrl": "http://www.samtrans.com/Developer/DLA-PP-SamTrans.html",
    "downloadPageUrl": "http://www.samtrans.com/Developer/DLA-PP-SamTrans.html?IsSubmitted=True"
  },
  "operatorsInFeed": [
    {
      "operator": {
        "name": "San Mateo County Transit District",
        "tags": {
          "us_national_transit_database_id": 9009,
          "website": "http://www.samtrans.com",
          "timezone": "America/Los_Angeles"
        },
        "identifiers": [
          { "identifier": "SamTrans" }
        ],
        "onestop_id": "o-9q9-SamTrans",
        "geometry": {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-122.51796,37.53556],[-122.412922,37.259608],[-122.3925,37.2503],[-122.382827,37.251686],[-122.21142,37.36789],[-122.19961,37.37708],[-122.194621,37.381745],[-122.12492,37.45734],[-122.13037,37.47045],[-122.13207,37.47271],[-122.39243,37.79009],[-122.39695,37.790137],[-122.39728,37.7901],[-122.41845,37.77518],[-122.48333,37.72698],[-122.485105,37.724185],[-122.49301,37.68985],[-122.515757,37.569983],[-122.51796,37.53556]]]}}
      },
      "gtfsAgencyId": "SamTrans"
    }
  ]
}
