=== brechtvdv/transitland-feed-registry/validator/json-schemas/feeds.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Transitland Onestop-Registry Feed",
  "type": "object",
  "required": ["onestopId", "url", "feedFormat", "operatorsInFeed"],
  "properties": {
    "onestopId": {
      "type": "string",
      "format": "feedOnestopId"
    },
    "url": {
      "type": "string",
      "format": "uri"
    },
    "feedFormat": { "type": "string" },
    "tags": { "type": "object" },
    "sha1": {
      "type": "string",
      "format": "sha1"
    },
    "operatorsInFeed": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["onestopId", "gtfsAgencyId"],
        "properties": {
          "gtfsAgencyId": { "type": "string" },
          "onestopId": {
            "type": "string",
            "format": "operatorOnestopId"
          },
          "identifiers": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== brechtvdv/transitland-feed-registry/feeds/f-lacmta.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-9q5-lacmta",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "metrolosangeles",
            "onestopId": "o-9q5-metrolosangeles"
        }
    ],
    "sha1": "201b718c6b8e08910da24d5714a1ac9287698b4a",
    "tags": {},
    "url": "http://developer.metro.net/gtfs/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-translink.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-c28-translink",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "westcoastexpress",
            "onestopId": "o-c2b-westcoastexpress"
        },
        {
            "gtfsAgencyId": "britishcolumbiarapidtransitcompany",
            "onestopId": "o-c2b8-britishcolumbiarapidtransitcompany"
        },
        {
            "gtfsAgencyId": "translink",
            "onestopId": "o-c28-translink"
        }
    ],
    "sha1": "066a5724657578e0b5efa2f830f27aa637974b58",
    "tags": {},
    "url": "http://mapexport.translink.bc.ca/current/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-9q9-VTA.json
{
  "onestopId": "f-9q9-VTA",
  "url": "http://www.vta.org/sfc/servlet.shepherd/document/download/069A0000001NUea",
  "feedFormat": "gtfs",
  "tags": {
    "licenseUrl": "http://www.sfmta.com/about-sfmta/reports/gtfs-transit-data",
    "downloadPageUrl": "http://www.vta.org/getting-around/gtfs-info/data-file"
  },
  "operatorsInFeed": [
    {
      "onestopId": "o-9q9-VTA",
      "gtfsAgencyId": "VTA"
    }
  ]
}

=== brechtvdv/transitland-feed-registry/feeds/f-9vk-mtaharriscounty.json
{
  "feedFormat": "gtfs",
  "onestopId": "f-9vk-mtaharriscounty",
  "operatorsInFeed": [
    {
      "gtfsAgencyId": "metropolitantransitauthorityofharriscounty",
      "onestopId": "o-9vk-metropolitantransitauthorityofharriscounty",
      "identifiers": [
        "usntd://6008"
      ]
    }
  ],
  "tags": {},
  "url": "http://www.ridemetro.org/News/Downloads/DataFiles/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-trimet.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-c20-trimet",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "trimet",
            "onestopId": "o-c20-trimet"
        }
    ],
    "sha1": "4e918ec81d80b5da6f7c35c35af0c16f74566d58",
    "tags": {},
    "url": "http://developer.trimet.org/schedule/gtfs.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-9q8y-SFMTA.json
{
  "onestopId": "f-9q8y-SFMTA",
  "url": "http://archives.sfmta.com/transitdata/google_transit.zip",
  "feedFormat": "gtfs",
  "tags": {
    "licenseUrl": "http://www.sfmta.com/about-sfmta/reports/gtfs-transit-data"
  },
  "operatorsInFeed": [
    {
      "onestopId": "o-9q8y-SFMTA",
      "gtfsAgencyId": "SFMTA"
    }
  ]
}

=== brechtvdv/transitland-feed-registry/feeds/f-9q9-bayarearapidtransit.json
{
  "feedFormat": "gtfs",
  "onestopId": "f-9q9-bayarearapidtransit",
  "operatorsInFeed": [
    {
      "gtfsAgencyId": "BART",
      "onestopId": "o-9q9-bayarearapidtransit",
      "identifiers": [
        "usntd://9003"
      ]
    }
  ],
  "tags": {},
  "url": "http://www.bart.gov/dev/schedules/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-dnh-marta.json
{
  "feedFormat": "gtfs",
  "onestopId": "f-dnh-marta",
  "operatorsInFeed": [
    {
      "gtfsAgencyId": "metropolitanatlantarapidtransitauthority",
      "onestopId": "o-dnh-metropolitanatlantarapidtransitauthority",
      "identifiers": [
        "usntd://4022"
      ]
    }
  ],
  "tags": {},
  "url": "http://www.itsmarta.com/google_transit_feed/google_transit.zip"
}
