=== brechtvdv/transitland-feed-registry/validator/json-schemas/feeds.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Transitland Onestop-Registry Feed",
  "type": "object",
  "required": ["onestopId", "url", "feedFormat", "operatorsInFeed"],
  "properties": {
    "onestopId": {
      "type": "string",
      "format": "feedOnestopId"
    },
    "url": {
      "type": "string",
      "format": "uri"
    },
    "feedFormat": { "type": "string" },
    "tags": { "type": "object" },
    "sha1": {
      "type": "string",
      "format": "sha1"
    },
    "operatorsInFeed": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["onestopId", "gtfsAgencyId"],
        "properties": {
          "gtfsAgencyId": { "type": "string" },
          "onestopId": {
            "type": "string",
            "format": "operatorOnestopId"
          },
          "identifiers": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== brechtvdv/transitland-feed-registry/feeds/f-dhw-miamidade.json
{
  "feedFormat": "gtfs",
  "onestopId": "f-dhw-miamidade",
  "operatorsInFeed": [
    {
      "gtfsAgencyId": "Miami Dade Transit",
      "onestopId": "o-dhw-miamidadetransit",
      "identifiers": [
        "usntd://4034"
      ]
    }
  ],
  "tags": {},
  "url": "http://www.miamidade.gov/transit/googletransit/current/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-mbta.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-drt-mbta",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "massport",
            "onestopId": "o-drt3p-massport"
        },
        {
            "gtfsAgencyId": "mbta",
            "onestopId": "o-drt-mbta"
        }
    ],
    "sha1": "d2b8860304aa3eb12fefa8a581f5c6dee978a6bc",
    "tags": {},
    "url": "http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-9q9-BART.json
{
  "onestopId": "f-9q9-BART",
  "url": "http://www.bart.gov/dev/schedules/google_transit.zip",
  "feedFormat": "gtfs",
  "tags": {
    "licenseUrl": "http://www.bart.gov/schedules/developers/developer-license-agreement",
    "downloadPageUrl": "http://www.bart.gov/schedules/developers/gtfs",
    "gtfs_data_exchange_id": "bay-area-rapid-transit"
  },
  "operatorsInFeed": [
    {
      "onestopId": "o-9q9-BART",
      "gtfsAgencyId": "BART"
    }
  ]
}

=== brechtvdv/transitland-feed-registry/feeds/f-samtrans.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-9q8-samtrans",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "samtrans",
            "onestopId": "o-9q8-samtrans"
        }
    ],
    "sha1": "535c2fd10837c1c9eba48cfd475509ae1868dc08",
    "tags": {
        "downloadPageUrl": "http://www.samtrans.com/Developer/DLA-PP-SamTrans.html?IsSubmitted=True",
        "licenseUrl": "http://www.samtrans.com/Developer/DLA-PP-SamTrans.html"
    },
    "url": "http://www.samtrans.com/Assets/GTFS/samtrans/SamTrans-GTFS.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-mtssandiego.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-9mu-mtssandiego",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "mts",
            "onestopId": "o-9mu-mts"
        }
    ],
    "sha1": "2193fe822834db036fbb951fd1c267560e6de6ff",
    "tags": {},
    "url": "http://www.sdmts.com/google_transit_files/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-dr5r-mtanyctbusstatenisland.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-dr5r-mtanyctbusstatenisland",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "MTA NYCT",
            "identifiers": [],
            "onestopId": "o-dr5r-mtanewyorkcitytransit"
        }
    ],
    "tags": {},
    "url": "http://web.mta.info/developers/data/nyct/bus/google_transit_staten_island.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-dq-mtamaryland.json
{
  "feedFormat": "gtfs",
  "onestopId": "f-dq-mtamaryland",
  "operatorsInFeed": [
    {
      "gtfsAgencyId": "mtaofficeoflocaltransitsupport",
      "onestopId": "o-dq-mtaofficeoflocaltransitsupport",
      "identifiers": []
    },
    {
      "gtfsAgencyId": "marylandtransitadministration",
      "onestopId": "o-dqc-marylandtransitadministration",
      "identifiers": [
        "usntd://3034"
      ]
    }
  ],
  "tags": {},
  "url": "http://mta.maryland.gov/_googletransit/latest/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-vta.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-9q9-vta",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "vta",
            "onestopId": "o-9q9-vta"
        }
    ],
    "sha1": "5ac0244cec6ae8dc7e06f6d277e4634f46e6b01c",
    "tags": {
        "downloadPageUrl": "http://www.vta.org/getting-around/gtfs-info/data-file",
        "licenseUrl": "http://www.sfmta.com/about-sfmta/reports/gtfs-transit-data"
    },
    "url": "http://www.vta.org/sfc/servlet.shepherd/document/download/069A0000001NUea"
}
