=== brechtvdv/transitland-feed-registry/validator/json-schemas/feeds.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Transitland Onestop-Registry Feed",
  "type": "object",
  "required": ["onestopId", "url", "feedFormat", "operatorsInFeed"],
  "properties": {
    "onestopId": {
      "type": "string",
      "format": "feedOnestopId"
    },
    "url": {
      "type": "string",
      "format": "uri"
    },
    "feedFormat": { "type": "string" },
    "tags": { "type": "object" },
    "sha1": {
      "type": "string",
      "format": "sha1"
    },
    "operatorsInFeed": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["onestopId", "gtfsAgencyId"],
        "properties": {
          "gtfsAgencyId": { "type": "string" },
          "onestopId": {
            "type": "string",
            "format": "operatorOnestopId"
          },
          "identifiers": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== brechtvdv/transitland-feed-registry/feeds/f-dr72-mtanyctbusbronx.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-dr72-mtanyctbusbronx",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "MTA NYCT",
            "identifiers": [],
            "onestopId": "o-dr5r-mtanewyorkcitytransit"
        }
    ],
    "tags": {},
    "url": "http://web.mta.info/developers/data/nyct/bus/google_transit_bronx.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-c28-translink.json
{
  "feedFormat": "gtfs",
  "onestopId": "f-c28-translink",
  "operatorsInFeed": [
    {
      "gtfsAgencyId": "translink",
      "onestopId": "o-c28-translink",
      "identifiers": []
    },
    {
      "gtfsAgencyId": "westcoastexpress",
      "onestopId": "o-c2b-westcoastexpress",
      "identifiers": []
    },
    {
      "gtfsAgencyId": "britishcolumbiarapidtransitcompany",
      "onestopId": "o-c2b8-britishcolumbiarapidtransitcompany",
      "identifiers": []
    }
  ],
  "sha1": "ae9eacad3c75b7fb9e506eacc5bed97ee5b965c2",
  "tags": {},
  "url": "http://mapexport.translink.bc.ca/current/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-9q9-SamTrans.json
{
  "onestopId": "f-9q9-SamTrans",
  "url": "http://www.samtrans.com/Assets/GTFS/samtrans/SamTrans-GTFS-RB115-rev-08252014.zip",
  "feedFormat": "gtfs",
  "tags": {
    "licenseUrl": "http://www.samtrans.com/Developer/DLA-PP-SamTrans.html",
    "downloadPageUrl": "http://www.samtrans.com/Developer/DLA-PP-SamTrans.html?IsSubmitted=True"
  },
  "operatorsInFeed": [
    {
      "onestopId": "o-9q9-SamTrans",
      "gtfsAgencyId": "SamTrans"
    }
  ]
}

=== brechtvdv/transitland-feed-registry/feeds/f-9q9-ACTransit.json
{
  "onestopId": "f-9q9-ACTransit",
  "url": "http://www.actransit.org/wp-content/uploads/gtfsdec072014b.zip",
  "feedFormat": "gtfs",
  "tags": {
    "license": "Creative Commons Attribution 3.0 Unported License",
    "licenseUrl": "http://www.actransit.org/data-terms-and-conditions/"
  },
  "operatorsInFeed": [
    {
      "onestopId": "o-9q9-ACTransit",
      "gtfsAgencyId": "AC Transit"
    }
  ]
}

=== brechtvdv/transitland-feed-registry/feeds/f-wmata.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-dqc-fwmata",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "dccirculator",
            "onestopId": "o-dqcjr-dccirculator"
        },
        {
            "gtfsAgencyId": "met",
            "onestopId": "o-dqc-met"
        }
    ],
    "sha1": "1827b2feceb1d9d2f2d69fbb984220675499e19d",
    "tags": {},
    "url": "http://lrg.wmata.com/GTFS_data/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-dr5r-mtanyctbusbrooklyn.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-dr5r-mtanyctbusbrooklyn",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "MTA NYCT",
            "identifiers": [],
            "onestopId": "o-dr5r-mtanewyorkcitytransit"
        }
    ],
    "tags": {},
    "url": "http://web.mta.info/developers/data/nyct/bus/google_transit_brooklyn.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-miamidade.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-dhw-miamidade",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "miamidadetransit",
            "onestopId": "o-dhw-miamidadetransit"
        }
    ],
    "sha1": "f30f191d45b27493b77a99a23a25be2bd87bbad5",
    "tags": {},
    "url": "http://www.miamidade.gov/transit/googletransit/current/google_transit.zip"
}

=== brechtvdv/transitland-feed-registry/feeds/f-mtamaryland.json
{
    "feedFormat": "gtfs",
    "onestopId": "f-dq-mtamaryland",
    "operatorsInFeed": [
        {
            "gtfsAgencyId": "marylandtransitadministration",
            "onestopId": "o-dqc-marylandtransitadministration"
        },
        {
            "gtfsAgencyId": "mtaofficeoflocaltransitsupport",
            "onestopId": "o-dq-mtaofficeoflocaltransitsupport"
        }
    ],
    "sha1": "7d65a94ee0924e7a17b3d0ba1f481210e609b041",
    "tags": {},
    "url": "http://mta.maryland.gov/_googletransit/latest/google_transit.zip"
}
